# poimandres palette
cursor-color = #E4F0FB
cursor-text = #1B1E28
background = #1B1E28
foreground = #A6ACCD
selection-background = #303340
selection-foreground = #E4F0FB
palette = 0=#171922
palette = 1=#D0679D
palette = 2=#5DE4C7
palette = 3=#FFFAC2
palette = 4=#ADD7FF
palette = 5=#D0679D
palette = 6=#89DDFF
palette = 7=#A6ACCD
palette = 8=#303340
palette = 9=#D0679D
palette = 10=#5DE4C7
palette = 11=#FFFAC2
palette = 12=#ADD7FF
palette = 13=#D0679D
palette = 14=#89DDFF
palette = 15=#E4F0FB
