# ─── Cyberdream ─────────────────────────────────────────────────────
# https://github.com/scottmckendry/cyberdream.nvim

cursor                    #ffffff
cursor_text_color         #16181a

background                #16181a
foreground                #ffffff
selection_background      #3c4048
selection_foreground      #ffffff
url_color                 #5ea1ff

color0   #16181a
color1   #ff6e5e
color2   #5eff6c
color3   #f1ff5e
color4   #5ea1ff
color5   #bd5eff
color6   #5ef1ff
color7   #ffffff
color8   #3c4048
color9   #ff6e5e
color10  #5eff6c
color11  #f1ff5e
color12  #5ea1ff
color13  #bd5eff
color14  #5ef1ff
color15  #ffffff

active_tab_foreground     #000000
active_tab_background     #ffbd5e
inactive_tab_foreground   #ffffff
inactive_tab_background   #16181a
tab_bar_background        #16181a
tab_title_template        " {fmt.fg._5ea1ff}{fmt.bold}{index}{fmt.nobold}{fmt.fg.tab} {title[:22]} "
active_tab_title_template " {fmt.fg._000000}{fmt.bold}⬡ {index} {title[:22]}{fmt.nobold} "
