# ─── Everblush ──────────────────────────────────────────────────────
# https://github.com/Everblush/everblush

cursor                    #6cbfbf
cursor_text_color         #141b1e

background                #141b1e
foreground                #dadada
selection_background      #2d3437
selection_foreground      #dadada
url_color                 #6cbfbf

color0   #232a2d
color1   #e57474
color2   #8ccf7e
color3   #e5c76b
color4   #67b0e8
color5   #c47fd5
color6   #6cbfbf
color7   #b3b9b8
color8   #2d3437
color9   #ef7e7e
color10  #96d988
color11  #f4d47a
color12  #71baef
color13  #ce89df
color14  #76c9c9
color15  #c4caca

active_tab_foreground     #141b1e
active_tab_background     #6cbfbf
inactive_tab_foreground   #b3b9b8
inactive_tab_background   #232a2d
tab_bar_background        #141b1e
tab_title_template        " {fmt.fg._6cbfbf}{fmt.bold}{index}{fmt.nobold}{fmt.fg.tab} {title[:22]} "
active_tab_title_template " {fmt.fg._141b1e}{fmt.bold}⬡ {index} {title[:22]}{fmt.nobold} "
