# ─── Poimandres ──────────────────────────────────────────────────────
# https://github.com/olivercederborg/poimandres.nvim

cursor                    #E4F0FB
cursor_text_color         #1B1E28

background                #1B1E28
foreground                #A6ACCD
selection_background      #303340
selection_foreground      #E4F0FB
url_color                 #ADD7FF

color0   #171922
color1   #D0679D
color2   #5DE4C7
color3   #FFFAC2
color4   #ADD7FF
color5   #D0679D
color6   #89DDFF
color7   #A6ACCD
color8   #303340
color9   #D0679D
color10  #5DE4C7
color11  #FFFAC2
color12  #ADD7FF
color13  #D0679D
color14  #89DDFF
color15  #E4F0FB

active_tab_foreground     #1B1E28
active_tab_background     #5DE4C7
inactive_tab_foreground   #A6ACCD
inactive_tab_background   #1B1E28
tab_bar_background        #171922
tab_title_template        " {fmt.fg._ADD7FF}{fmt.bold}{index}{fmt.nobold}{fmt.fg.tab} {title[:22]} "
active_tab_title_template " {fmt.fg._1B1E28}{fmt.bold}⬡ {index} {title[:22]}{fmt.nobold} "
